//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace week_6_1_code_challenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameScores1
    {
        public int GameScoreID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Score { get; set; }
        public string Game { get; set; }
        public System.DateTime Date { get; set; }
    }
}
